version: '3.8'

services:
  fast-ocr:
    image: ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPO}:latest
    container_name: fast-ocr-app
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G