version: '3.8'

services:
  fast-ocr:
    build:
      context: .
      dockerfile: Dockerfile
    image: fast-ocr:latest
    container_name: fast-ocr-app
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount for development - comment out for production
      - ./main.py:/app/main.py:ro
    # Uncomment to use pre-built image from GHCR instead of building
    # image: ghcr.io/YOUR_USERNAME/fast-ocr:latest